<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
*/
$config['base_url']	= isset($_SERVER['HTTP_HOST']) ? '//' . $_SERVER['HTTP_HOST'] . '/' : '';
$config['base_download_url'] = isset($_SERVER['HTTP_HOST']) ? '//' . $_SERVER['HTTP_HOST'] . '/' : '';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of "AUTO" works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/

//$config['uri_protocol']	= 'REQUEST_URI';
$config['uri_protocol']    = isset($_SERVER['REQUEST_URI']) ? 'REQUEST_URI' : 'CLI';
/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '.html';

/*
|--------------------------------------------------------------------------
| Languages Settings
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['support_languages'] = array('en'=>'english', 'it'=>'italian'/*,'ru'=>'russian'*/);
$config['default_language'] = 'en';
$config['language'] = $config['support_languages'][$config['default_language']];

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the "hooks" feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9?~%.:+_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string "words" that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['directory_trigger'] = 'd';	 // experimental not currently in use
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to 
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/logs/ folder.  Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';


/**
 * if !empty, should contain email where send log info
 * possible values:
 * false, null, 0, "" => no emaul log
 * "email@email.com" => one email where to send log
 * [email1@email.com, email2@email.com] => array of emails where to send logs
 */
$config['log_emails'] = ["nikita.bunenkov@boldendeavours.com", "dan@naturefootage.com", "boris.kovalenko@boldendeavours.com"];

/**
 * flag determines should 404 status be logged to email as common error
 */
$config['log_email_404'] = false;

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Sessions class with encryption
| enabled you MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'l5F0Vb1s7Pg59X9m';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'session_cookie_name' = the name you want for the cookie
| 'encrypt_sess_cookie' = TRUE/FALSE (boolean).  Whether to encrypt the cookie
| 'session_expiration'  = the number of SECONDS you want the session to last.
|  by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ri_session';
$config['sess_expiration']		= 43200; // 12 hours
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= TRUE;
$config['sess_table_name']		= 'lib_sessions';
$config['sess_match_ip']		= TRUE;
$config['sess_match_useragent']	= FALSE;
$config['sess_time_to_update'] 	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not "echo" any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are "local" or "gmt".  This pref tells the system whether to use
| your server's local time as the master "now" reference, or convert it to
| GMT.  See the "date helper" page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Service pathes
|--------------------------------------------------------------------------
|
*/
$config['menu_path'] = 'data/upload/menu/';  
$config['menu_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['menu_path']; 

$config['help_path'] = 'data/upload/help/';  
$config['help_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['help_path']; 

$config['cat_path'] = 'data/upload/cats/'; 
$config['cat_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['cat_path'];

$config['highlights_path'] = 'data/upload/highlights/';
$config['highlights_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['highlights_path'];

$config['disk_path'] = 'data/upload/disks/'; 
$config['disk_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['disk_path']; 

$config['image_path'] = 'data/upload/resources/image/';
$config['image_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['image_path']; 

$config['clip_path'] = 'data/upload/resources/clip/';
$config['clip_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['clip_path'];

$config['banner_path'] = 'data/upload/tb/';
$config['banner_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['banner_path'];

$config['temp_path'] = 'data/upload/temp/';
$config['temp_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['temp_path']; 

$config['wm_path'] = 'data/upload/watermark/';  
$config['wm_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['wm_path'];  

$config['avatar_path'] = 'data/upload/avatars/';  
$config['avatar_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['avatar_path'];

$config['features_path'] = '/data/upload/features/';
$config['features_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['features_path'];

//$config['converted_clips'] = $_SERVER['DOCUMENT_ROOT'] . '/data/upload/resources/converted/';
$config['converted_clips'] = $_SERVER['DOCUMENT_ROOT'] . '/data/upload/resources/clip/converted/';

$config['log_dir'] = $_SERVER['DOCUMENT_ROOT'].'/data/log/';

$config['seo_dir'] = $_SERVER['DOCUMENT_ROOT'].'/data/seo/';

$config['attachments_path'] = 'data/upload/attachments/';
$config['attachments_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['attachments_path'];

$config['news_path'] = 'data/upload/news/';
$config['news_dir'] = $_SERVER['DOCUMENT_ROOT'].'/'.$config['news_path'];

/*
|--------------------------------------------------------------------------
| Sagepay settings
|--------------------------------------------------------------------------
|
*/
$config['Sagepay_ConnectTo'] = 'TEST';
$config['Sagepay_VirtualDir'] = '';
$config['Sagepay_YourSiteFQDN'] = $config['base_url'];
$config['Sagepay_VendorName'] = 'redhotproductio';
$config['Sagepay_EncryptionPassword'] = 'ckHA34iiYWa2GhES';
$config['Sagepay_VendorEMail'] = 'richard@rhp.uk.com';
$config['Sagepay_Description'] = 'Redhot Footage Cart';

/*
|--------------------------------------------------------------------------
| Paypal Express Checkout settings
|--------------------------------------------------------------------------
|
*/

$config['PP_SUBJECT'] = '';
$config['PP_USE_PROXY'] = false;
$config['PP_PROXY_HOST'] = '127.0.0.1';
$config['PP_PROXY_PORT'] = 808;
$config['PP_version'] = '65.1';
$config['PP_ACK_SUCCESS'] = 'SUCCESS';
$config['PP_ACK_SUCCESS_WITH_WARNING'] = 'SUCCESSWITHWARNING';

/* TEST */
$config['PP_API_UserName'] = 'seller_1248855758_biz_api1.live.com';
$config['PP_API_Password'] = '1248855767';
$config['PP_API_Signature'] = 'AUbW4auqvyUuPg6ehjlWCo0GVVV3ATpBbwaNm4-.8OsFMh5LA0B9cOqf';
$config['PP_API_Endpoint'] = 'https://api-3t.sandbox.paypal.com/nvp';
$config['PP_URL'] = 'https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token=';

/* LIVE
$config['PP_API_UserName'] = 'richard_api1.rhp.uk.com';
$config['PP_API_Password'] = 'GUETCE63CQKG5ZK7';
$config['PP_API_Signature'] = 'AcLWCgOJLS2wBIwgIzweGiGgo6a9AtnT0FpZs-f.hI9q.8bG0T0hZ3N9';
$config['PP_API_Endpoint'] = 'https://api-3t.paypal.com/nvp';
$config['PP_URL'] = 'https://www.paypal.com/webscr&cmd=_express-checkout&token= ';
*/

/*
|--------------------------------------------------------------------------
| Image sizes
|--------------------------------------------------------------------------
|
*/
$config['thumb_image_size'] = 100;
$config['preview_image_size'] = 400;

$config['enable_watermark'] = TRUE;
$config['watermark_color'] = '#ffffff';
$config['watermark_font_size'] = 17;
$config['watermark_opacity'] = 50;

/*
|--------------------------------------------------------------------------
| Clarifai settings
|--------------------------------------------------------------------------
|
*/
$config['clientId'] = 'Pjer6EFnvhRlSw-JzizFjd65PkTAkH84fMi-zYW-';
$config['clientSecrect'] = 'JIbgSpvrnq5G83VyYmYfdjhapBP-ugr8PKlgOJ__';
$config['minAccurate'] = 90;

//*-------------------------------------------------------------------------*/

$config['search_perpage'] = 12;
$config['use_qt'] = isset($_SERVER['HTTP_USER_AGENT']) ? strpos($_SERVER['HTTP_USER_AGENT'], 'iPad') || strpos($_SERVER['HTTP_USER_AGENT'], 'iPhone') : false;
$config['release_date'] = '201211071020';

$config['title'] = 'Big Easy Footage Library';
$config['vendor_name'] = 'Big Easy Footage Library';
$config['vendor_email'] = 'support@naturefootage.com';
$config['vendor_phone'] = '1.866.375.2313 Toll Free in U.S.A. +1.831.375.2313 Outside U.S.A. +1.831.621.9559 Fax';
$config['vendor_address'] =
    '1 Boroughbridge Road
Knaresborough
HG5 0LT
UK';
$config['vendor_vat_no'] = '987 6543 21';
$config['order_ref_prefix'] = 'BEFL';

$config['download_active_days'] = 30;
$config['user_folder_salt'] = '7D9n2lAx';
//$config['hd_path'] = 'C:/media/redhot/Clips/';

$config['s3_host'] = 's3.amazonaws.com';
$config['s3_cloudfront'] = 'video.naturefootage.com';
$config['svn_username'] = 'ivan';
$config['svn_password'] = 'be290';
$config['svn_frontend_repo'] = 'svn://svn.boldendeavours.com/repo/footagesearch-wp/trunk';

/* End of file config.php */
/* Location: ./system/application/config/config.php */
